version: '2'
services:
  webapp:
    build: .
    container_name: image-detection
    ports:
      - "9000:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - DB_ENDPOINT=mongodb://mongo/vision

  mongo:
    container_name: mongo
    image: mongo:3.6.0
    volumes:
      - mongodbdata:/data/db 
    ports:
      - "27017:27017"
    # restart: "always"
    
volumes:
  mongodbdata: 
